import type { CampusOption } from "@/types";

/**
 * Default campus list shown immediately in the school-setup step, before
 * (and independent of) the live /misc/campuses fetch — referenceStore seeds
 * its state with this so the step is usable at first paint instead of a
 * blank/skeleton list, and swaps in the real data the moment it arrives.
 * Label format matches what the real endpoint produces: "Name (TAG)".
 */
const NAMES: { name: string; tag: string }[] = [
  { name: "University of Lagos", tag: "unilag" },
  { name: "University of Ibadan", tag: "ui" },
  { name: "University of Nigeria, Nsukka", tag: "unn" },
  { name: "Obafemi Awolowo University", tag: "oau" },
  { name: "Ahmadu Bello University", tag: "abu" },
  { name: "University of Benin", tag: "uniben" },
  { name: "University of Port Harcourt", tag: "uniport" },
  { name: "University of Ilorin", tag: "unilorin" },
  { name: "Bayero University Kano", tag: "buk" },
  { name: "Nnamdi Azikiwe University", tag: "unizik" },
  { name: "University of Calabar", tag: "unical" },
  { name: "Federal University of Technology, Akure", tag: "futa" },
  { name: "Federal University of Technology, Minna", tag: "futminna" },
  { name: "Federal University of Technology, Owerri", tag: "futo" },
  { name: "University of Jos", tag: "unijos" },
  { name: "University of Maiduguri", tag: "unimaid" },
  { name: "Usmanu Danfodiyo University, Sokoto", tag: "udusok" },
  { name: "University of Uyo", tag: "uniuyo" },
  { name: "Federal University of Agriculture, Abeokuta", tag: "funaab" },
  { name: "Joseph Sarwuan Tarka University, Makurdi", tag: "jostum" },
  { name: "Michael Okpara University of Agriculture, Umudike", tag: "mouau" },
  { name: "Federal University, Oye-Ekiti", tag: "fuoye" },
  { name: "Federal University, Otuoke", tag: "fuotuoke" },
  { name: "Federal University, Dutse", tag: "fud" },
  { name: "Federal University, Dutsin-Ma", tag: "fudutsinma" },
  { name: "Federal University, Lokoja", tag: "fulokoja" },
  { name: "Federal University, Kashere", tag: "fukashere" },
  { name: "Alex Ekwueme Federal University, Ndufu-Alike", tag: "aefunai" },
  { name: "Federal University, Wukari", tag: "fuwukari" },
  { name: "Federal University, Gusau", tag: "fugusau" },
  { name: "Federal University, Gashua", tag: "fugashua" },
  { name: "Federal University, Birnin Kebbi", tag: "fubk" },
  { name: "Nigerian Defence Academy", tag: "nda" },
  { name: "National Open University of Nigeria", tag: "noun" },
  { name: "Federal University of Petroleum Resources, Effurun", tag: "fupre" },
  { name: "University of Abuja", tag: "uniabuja" },
  { name: "Modibbo Adama University, Yola", tag: "mau" },
  { name: "Abubakar Tafawa Balewa University, Bauchi", tag: "atbu" },
  { name: "Federal University, Lafia", tag: "fulafia" },
  { name: "Federal University of Health Sciences, Otukpo", tag: "fuhso" },
  { name: "Federal University of Health Sciences, Azare", tag: "fuhsazare" },
  { name: "University of Medical Sciences, Ondo", tag: "unimed" },
  { name: "Umaru Musa Yar'adua University, Katsina", tag: "umyu" },
  { name: "Kano University of Science and Technology, Wudil", tag: "kust" },
  { name: "Ibrahim Badamasi Babangida University, Lapai", tag: "ibbul" },
  { name: "Lagos State University", tag: "lasu" },
  { name: "Rivers State University", tag: "rsu" },
  { name: "Delta State University", tag: "delsu" },
  { name: "Ekiti State University", tag: "eksu" },
  { name: "Ambrose Alli University, Ekpoma", tag: "aau" },
  { name: "Olabisi Onabanjo University", tag: "oou" },
  { name: "Ladoke Akintola University of Technology", tag: "lautech" },
  { name: "Enugu State University of Science and Technology", tag: "esut" },
  { name: "Imo State University", tag: "imsu" },
  { name: "Abia State University", tag: "absu" },
  { name: "Ebonyi State University", tag: "ebsu" },
  { name: "Benue State University", tag: "bsu" },
  { name: "Kaduna State University", tag: "kasu" },
  { name: "Kwara State University", tag: "kwasu" },
  { name: "Osun State University", tag: "uniosun" },
  { name: "Adekunle Ajasin University, Akungba", tag: "aaua" },
  { name: "Tai Solarin University of Education", tag: "tasued" },
  { name: "Adamawa State University", tag: "adsu" },
  { name: "Akwa Ibom State University", tag: "aksu" },
  { name: "Cross River University of Technology", tag: "crutech" },
  { name: "Plateau State University, Bokkos", tag: "plasu" },
  { name: "Nasarawa State University, Keffi", tag: "nsuk" },
  { name: "Niger Delta University", tag: "ndu" },
  { name: "Bauchi State University, Gadau", tag: "basug" },
  { name: "Gombe State University", tag: "gsu" },
  { name: "Sokoto State University", tag: "ssu" },
  { name: "Taraba State University", tag: "tsu" },
  { name: "Yobe State University", tag: "ysu" },
  { name: "Zamfara State University", tag: "zamsu" },
  { name: "Kebbi State University of Science and Technology", tag: "ksusta" },
  { name: "Prince Abubakar Audu University, Anyigba", tag: "paau" },
  { name: "Ignatius Ajuru University of Education", tag: "iaue" },
  { name: "Chukwuemeka Odumegwu Ojukwu University", tag: "coou" },
  { name: "Edo State University, Uzairue", tag: "edsu" },
  { name: "Moshood Abiola University of Science and Technology", tag: "maustech" },
  { name: "Covenant University", tag: "cu" },
  { name: "Babcock University", tag: "babcock" },
  { name: "Redeemer's University", tag: "run" },
  { name: "Landmark University", tag: "lmu" },
  { name: "Bowen University", tag: "bowen" },
  { name: "Afe Babalola University", tag: "abuad" },
  { name: "Bells University of Technology", tag: "bellstech" },
  { name: "Pan-Atlantic University", tag: "pau" },
  { name: "American University of Nigeria", tag: "aun" },
  { name: "Nile University of Nigeria", tag: "nun" },
  { name: "Lead City University", tag: "lcu" },
  { name: "Caleb University", tag: "caleb" },
  { name: "Crawford University", tag: "crawford" },
  { name: "Elizade University", tag: "elizade" },
  { name: "Wesley University", tag: "wesley" },
  { name: "Veritas University", tag: "veritas" },
  { name: "Baze University", tag: "baze" },
  { name: "Novena University", tag: "novena" },
  { name: "Salem University", tag: "salem" },
  { name: "Al-Hikmah University", tag: "alhikmah" },
];

export const DEFAULT_CAMPUSES: CampusOption[] = NAMES.map(({ name, tag }) => ({
  label: `${name} (${tag.toUpperCase()})`,
  tag,
}));
