import type { Major } from "@/types";

/**
 * Default majors list shown immediately in the academics-setup step, before
 * (and independent of) the live /misc/majors fetch — referenceStore seeds
 * its state with this so the step is usable at first paint instead of a
 * blank/skeleton chip row, and swaps in the real data the moment it arrives.
 */
const NAMES = [
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Cybersecurity",
  "Data Science",
  "Information Systems",
  "Computer Engineering",
  "Mechatronics Engineering",
  "Physics",
  "Industrial Physics",
  "Physics with Electronics",
  "Chemistry",
  "Industrial Chemistry",
  "Biochemistry",
  "Microbiology",
  "Botany",
  "Zoology",
  "Biology",
  "Marine Biology",
  "Fisheries and Aquaculture",
  "Environmental Biology",
  "Mathematics",
  "Statistics",
  "Mathematics and Computer Science",
  "Geology",
  "Geophysics",
  "Applied Geophysics",
  "Meteorology",
  "Science Laboratory Technology",
  "Astronomy and Astrophysics",
  "Electrical Engineering",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Petroleum and Gas Engineering",
  "Biomedical Engineering",
  "Agricultural Engineering",
  "Metallurgical and Materials Engineering",
  "Telecommunications Engineering",
  "Systems Engineering",
  "Marine Engineering",
  "Automotive Engineering",
  "Structural Engineering",
  "Water Resources and Environmental Engineering",
  "Food Engineering",
  "Textile Engineering",
  "Mining Engineering",
  "Polymer and Textile Engineering",
  "Aerospace Engineering",
  "Production Engineering",
  "Industrial and Production Engineering",
  "Welding and Fabrication Engineering",
  "Computer and Electronics Engineering",
  "Medicine and Surgery",
  "Nursing Science",
  "Pharmacy",
  "Dentistry",
  "Physiology",
  "Anatomy",
  "Medical Laboratory Science",
  "Radiography",
  "Physiotherapy",
  "Public Health",
  "Environmental Health Science",
  "Nutrition and Dietetics",
  "Optometry",
  "Human Kinetics and Health Education",
  "Veterinary Medicine",
  "Nursing and Midwifery",
  "Prosthetics and Orthotics",
  "Speech and Language Therapy",
  "Audiology",
  "Community Health",
  "Agricultural Economics",
  "Crop Science",
  "Animal Science",
  "Soil Science",
  "Agricultural Extension and Rural Development",
  "Forestry and Wildlife Management",
  "Fisheries",
  "Food Science and Technology",
  "Home Science and Management",
  "Agribusiness",
  "Plant Science and Biotechnology",
  "Horticulture",
  "Aquaculture and Fisheries Management",
  "Agricultural Biochemistry",
  "Wildlife and Ecotourism Management",
  "Architecture",
  "Estate Management",
  "Urban and Regional Planning",
  "Quantity Surveying",
  "Building Technology",
  "Surveying and Geoinformatics",
  "Environmental Management",
  "Landscape Architecture",
  "Fine and Applied Arts",
  "Industrial Design",
  "Urban Design",
  "Environmental Science",
  "Law",
  "Political Science",
  "International Relations",
  "Public Administration",
  "Economics",
  "Sociology",
  "Psychology",
  "Criminology and Security Studies",
  "Social Work",
  "Demography and Social Statistics",
  "Peace and Conflict Studies",
  "Local Government Studies",
  "International Law and Diplomacy",
  "Development Studies",
  "Gender Studies",
  "Accounting",
  "Banking and Finance",
  "Business Administration",
  "Marketing",
  "Insurance",
  "Actuarial Science",
  "Human Resource Management",
  "Entrepreneurship",
  "Taxation",
  "Cooperative Economics and Management",
  "Office and Information Management",
  "Procurement and Supply Chain Management",
  "Transport Management",
  "Hospitality and Tourism Management",
  "Shipping and Maritime Management",
  "Business Education",
  "Industrial Relations and Personnel Management",
  "Project Management",
  "Mass Communication",
  "English Language",
  "Linguistics",
  "History and International Studies",
  "Philosophy",
  "Theatre Arts",
  "Music",
  "French",
  "Religious Studies",
  "Christian Religious Studies",
  "Islamic Studies",
  "Arabic Studies",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Library and Information Science",
  "Archaeology and Anthropology",
  "Communication and Language Arts",
  "Creative Arts",
  "Broadcasting",
  "Education and Computer Science",
  "Education and Economics",
  "Education and English Language",
  "Education and Biology",
  "Education and Chemistry",
  "Education and Physics",
  "Education and Mathematics",
  "Education and Political Science",
  "Guidance and Counselling",
  "Adult Education",
  "Educational Management",
  "Early Childhood Education",
  "Special Education",
  "Vocational and Technical Education",
  "Health Education",
  "Physical and Health Education",
  "Library Science Education",
  "Education and French",
  "Education and History",
  "Agricultural Education",
  "Nautical Science",
  "Ship Operations",
  "Petroleum Marketing and Business Studies",
  "Cyber Security and Information Technology",
  "Software Development",
  "Artificial Intelligence",
  "Robotics Engineering",
  "Renewable Energy Engineering",
  "Biotechnology",
  "Nanotechnology",
  "Forensic Science",
  "Criminal Justice",
  "Diplomatic Studies",
  "Actuarial and Insurance Science",
  "Real Estate and Facilities Management",
  "Building Services Engineering",
  "Ceramics and Glass Technology",
  "Textile Design",
  "Fashion Design and Textile Technology",
  "Culinary Arts",
  "Event Management",
  "Sports Science",
  "Kinesiology",
  "Music Technology",
  "Film and Multimedia Studies",
];

export const DEFAULT_MAJORS: Major[] = NAMES.map((major_name) => ({
  major_name,
  major_tag: major_name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, ""),
}));
